# -*- coding: utf-8 -*-
"""A test child process that CANNOT reach the network (RC-3 MED-3).

WHY THIS FILE EXISTS
    `StartupMatrix._start` runs the real entrypoint in a subprocess and
    passed `os.environ` through, minus seven keys. `KALSHI_KEY_ID` and
    `KALSHI_PRIVATE_KEY` were not among the seven, and
    `prod_credentials_config()` accepts any non-empty key id plus any
    well-formed RSA PEM. The independent reviewer confirmed by execution that
    on a machine with production credentials exported, three of those tests
    boot far enough to issue AUTHENTICATED `GET /portfolio/balance` and
    `GET /portfolio/positions` against the real production account, for up to
    the 180 s subprocess timeout, three times per run.

    Reads only — read-only mode held and no write authorization existed — but
    "the tests do not touch the broker" was a property of CI happening to
    have no credentials, not a property of the tests. Running the suite on an
    operator's laptop is not supposed to be a different act from running it
    in CI.

WHAT THIS PROVIDES
    `sitecustomize.py` source that Python imports automatically at
    interpreter start, before any application code, which makes DNS and
    socket connection raise. A blocked attempt is appended to the file named
    by `ATLAS_TEST_NETWORK_LOG`, so a test can assert not merely that nothing
    reached Kalshi but that nothing was even ATTEMPTED — and can name the
    host if something was.

    Two independent layers, because either alone can be bypassed: name
    resolution (`getaddrinfo`) and connection (`socket.connect`,
    `create_connection`). A caller with a hard-coded IP still hits the second.
"""

import os

#: Hostname fragments that identify the real broker. Used for REPORTING only.
#:
#: A broker-hostname check is NOT sufficient on its own and must never be the
#: guard: behind an HTTP proxy the host a client resolves is the proxy, so a
#: request on its way to Kalshi records `127.0.0.1` and names no Kalshi host
#: at all. Callers therefore assert `attempts() == []` — no outbound attempt
#: of ANY kind — and use these markers only to make a failure legible.
BROKER_HOST_MARKERS = ("kalshi.com", "kalshi.co", "elections.kalshi")

#: Written verbatim into the child's `sitecustomize.py`. Deliberately
#: dependency-free and defensive: a failure to install the block must be
#: LOUD, never a silently unguarded child.
SITECUSTOMIZE_SOURCE = '''\
# Generated by tests/_netblock.py -- blocks all outbound network in a test
# child process. Imported automatically by Python before any application code.
import os
import socket

_LOG = os.environ.get("ATLAS_TEST_NETWORK_LOG")


class NetworkBlockedInTests(RuntimeError):
    """Raised instead of contacting anything outside this process."""


def _record(target):
    if not _LOG:
        return
    try:
        with open(_LOG, "a", encoding="utf-8") as fh:
            fh.write(repr(target) + "\\n")
    except OSError:
        pass


def _blocked_getaddrinfo(host, port, *a, **k):
    _record(("getaddrinfo", host, port))
    raise NetworkBlockedInTests(
        "DNS resolution is blocked in tests: %r:%r" % (host, port))


def _blocked_create_connection(address, *a, **k):
    _record(("create_connection",) + tuple(address or ()))
    raise NetworkBlockedInTests(
        "outbound connections are blocked in tests: %r" % (address,))


def _blocked_connect(self, address):
    _record(("connect",) + tuple(address if isinstance(address, tuple)
                                 else (address,)))
    raise NetworkBlockedInTests(
        "outbound connections are blocked in tests: %r" % (address,))


def _blocked_connect_ex(self, address):
    # Records like the other three. A silent hook would let an attempt through
    # `connect_ex` pass the `attempts() == []` assertion unseen -- isolation
    # would hold, but the evidence for it would be blind.
    _record(("connect_ex",) + tuple(address if isinstance(address, tuple)
                                    else (address,)))
    return 1


socket.getaddrinfo = _blocked_getaddrinfo
socket.create_connection = _blocked_create_connection
socket.socket.connect = _blocked_connect
socket.socket.connect_ex = _blocked_connect_ex

# Proof the block INSTALLED in this child. `site.execsitecustomize()` swallows
# a non-ImportError failure here with only a stderr warning, so without a
# marker "no attempts recorded" is satisfied both by "guarded and quiet" and
# by "silently unguarded".
os.environ["ATLAS_NETBLOCK_INSTALLED"] = "1"
_record(("netblock-installed",))
'''

#: Credential and mode variables that must never reach a test child process.
#: `KALSHI_KEY_ID`/`KALSHI_PRIVATE_KEY` are the two the reviewer found
#: missing; the rest are stripped so the child's decision comes from the test
#: rather than from whatever the developer's shell happens to hold.
STRIPPED_ENV = (
    "KALSHI_KEY_ID", "KALSHI_PRIVATE_KEY",
    "KALSHI_API_KEY_ID", "KALSHI_API_PRIVATE_KEY",
    "PROD_ACCESS_MODE", "LIVE_TRADING", "LIVE_TRADING_CONFIRMED",
    "LIVE_BROKER_WRITES_AUTHORIZED", "KALSHI_ENV_CONFIRM",
    "MODEL_APPROVED", "MODEL_APPROVED_FOR_LIVE", "NO_LIVE_PROMOTION",
    "DEMO_TRADING",
    "RESTORE_STATE_TGZ_B64", "RESTORE_STATE_SHA256",
)

def install(tmpdir, env, network_log):
    """Write `sitecustomize.py` into `tmpdir` and return a hardened env copy.

    The child gets `tmpdir` first on `PYTHONPATH`, so the block is installed
    before `kalshi_alpha_bot` — or `requests`, or `socket` users of any kind —
    gets a chance to run.
    """
    with open(os.path.join(tmpdir, "sitecustomize.py"), "w",
              encoding="utf-8") as fh:
        fh.write(SITECUSTOMIZE_SOURCE)
    hardened = {k: v for k, v in env.items() if k not in STRIPPED_ENV}
    existing = hardened.get("PYTHONPATH", "")
    hardened["PYTHONPATH"] = (tmpdir + os.pathsep + existing if existing
                              else tmpdir)
    hardened["ATLAS_TEST_NETWORK_LOG"] = network_log
    return hardened


#: Sentinel the child writes at import to prove the block installed.
INSTALL_MARKER = "netblock-installed"


def installed(network_log):
    """True if the child actually installed the block (LOW-2)."""
    return any(INSTALL_MARKER in line for line in _lines(network_log))


def _lines(network_log):
    try:
        with open(network_log, encoding="utf-8") as fh:
            return [line.strip() for line in fh if line.strip()]
    except OSError:
        return []


def attempts(network_log):
    """Every blocked network attempt the child made, as raw text lines.

    Excludes the install marker, which is bookkeeping rather than an attempt.
    """
    return [line for line in _lines(network_log)
            if INSTALL_MARKER not in line]


def broker_attempts(network_log):
    """The subset of attempts naming the real broker."""
    return [line for line in attempts(network_log)
            if any(marker in line for marker in BROKER_HOST_MARKERS)]
